# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fc68d7b75e945326fa55eb300fc2042e7e7e1e725a4855a4f91286734916eceb4f9487787e6e1a8a1f0b67639e5a0b5cdc5343d105b0f232b9acd930d172f91

test:
  secret_key_base: 63e87a45f2e8f23951e62bd22e9f8fecc6b0655491b994ec41e3a10a04540bc2b502fce406329a7c26e1349e31c2f0c7fd005213c4552aa4861b729e6d1f7f0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
